# Generated by Django 5.2.3 on 2025-07-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cart_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_key',
        ),
    ]
