# Generated by Django 5.2.3 on 2025-07-31 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
