# Generated by Django 5.2.3 on 2025-08-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_cartitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='sold_count',
            field=models.IntegerField(default=0),
        ),
    ]
