# Generated by Django 5.2.3 on 2025-08-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_productvariant_sold_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantoption',
            name='type',
            field=models.CharField(choices=[('color', 'Color'), ('size', 'Size'), ('weight', 'Weight'), ('volume', 'Volume'), ('length', 'Length'), ('material', 'Material'), ('quantity', 'Quantity'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
    ]
