# Generated by Django 5.2.3 on 2025-08-06 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_variantoption_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantoption',
            name='type',
        ),
    ]
