# Generated by Django 5.2.3 on 2025-08-18 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_wishlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='promocode',
            name='usage_limit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
